<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-HRISQ2F" failures="0" tests="9" name="com.TestCases.ORGHRM_AddEmployee_And_EmployeeList" time="7.662" errors="2" timestamp="2023-05-11T16:59:37 IST" skipped="0">
  <testcase classname="com.TestCases.ORGHRM_AddEmployee_And_EmployeeList" name="LogInPage" time="2.712"/>
  <system-out/>
  <testcase classname="com.TestCases.ORGHRM_AddEmployee_And_EmployeeList" name="ORGHrmTest" time="0.030">
    <error message="Cannot invoke &quot;org.apache.poi.ss.usermodel.Row.createCell(int)&quot; because &quot;this.row&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Row.createCell(int)" because "this.row" is null
at com.TestCases.ORGHRM_AddEmployee_And_EmployeeList.ORGHrmTest(ORGHRM_AddEmployee_And_EmployeeList.java:90)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- ORGHrmTest -->
  <system-out/>
  <testcase classname="com.TestCases.ORGHRM_AddEmployee_And_EmployeeList" name="Admintest" time="0.038">
    <error message="Cannot invoke &quot;org.apache.poi.ss.usermodel.Row.createCell(int)&quot; because &quot;this.row&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Row.createCell(int)" because "this.row" is null
at com.TestCases.ORGHRM_AddEmployee_And_EmployeeList.Admintest(ORGHRM_AddEmployee_And_EmployeeList.java:142)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Admintest -->
  <system-out/>
  <testcase classname="com.TestCases.ORGHRM_AddEmployee_And_EmployeeList" name="AddEmployee" time="1.066"/>
  <system-out/>
  <testcase classname="com.TestCases.ORGHRM_AddEmployee_And_EmployeeList" name="AddEmployeeHeaderTest" time="0.043"/>
  <system-out/>
  <testcase classname="com.TestCases.ORGHRM_AddEmployee_And_EmployeeList" name="AddEmployeeFullNameTestData" time="0.038"/>
  <system-out/>
  <testcase classname="com.TestCases.ORGHRM_AddEmployee_And_EmployeeList" name="AddEmployeeFirstNameTestData" time="0.388"/>
  <system-out/>
  <testcase classname="com.TestCases.ORGHRM_AddEmployee_And_EmployeeList" name="AddEmployeeSaveTestData" time="3.261"/>
  <system-out/>
  <testcase classname="com.TestCases.ORGHRM_AddEmployee_And_EmployeeList" name="AddEmployeePersnolDetailsTest" time="0.086"/>
  <system-out/>
</testsuite> <!-- com.TestCases.ORGHRM_AddEmployee_And_EmployeeList -->
